# Generated by Django 5.1.2 on 2024-10-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_subtopic_post_subtopic_topic_subtopic_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.subtopic'),
        ),
    ]
